name: Build APK Absensi Pribadi

on:
  workflow_dispatch:
  push:
    branches:
      -build-apk.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Extract source ZIP
        run: |
          mkdir -p source
          unzip -o AbsensiPribadiPro2.2-Final-Android.zip -d source

      - name: Find Android project
        run: |
          GRADLEW=$(find source -name gradlew -type f | head -n 1)
          if [ -z "$GRADLEW" ]; then
            echo "gradlew tidak ditemukan"
            find source -maxdepth 3 -type f | head -100
            exit 1
          fi

          PROJECT_DIR=$(dirname "$GRADLEW")
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          chmod +x "$GRADLEW"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AbsensiPribadi-2.2-APK
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk
